{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mma.fullname" . }}-env
  labels:
    {{- include "mma.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end -}}
{{- if .Values.git.sshKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mma.fullname" . }}-git-ssh
  labels:
    {{- include "mma.labels" . | nindent 4 }}
type: Opaque
stringData:
  git_deploy: |-
    {{- .Values.git.sshKey | nindent 4 }}
  {{- if .Values.git.knownHosts }}
  known_hosts: |-
    {{- .Values.git.knownHosts | nindent 4 }}
  {{- end }}
{{- end -}}
